repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ^test/.*/
    -   id: trailing-whitespace
        exclude: ^test/.*/
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.1
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: prevent-version-commit
        name: Prevent committing checktestdata/__version__.py
        entry: >
            bash -c '
            git diff --cached --name-only | grep -q "^checktestdata/__version__.py$" &&
            { echo "Error: Do not commit __version__.py"; exit 1; } || exit 0
            '
        language: system
        files: checktestdata/__version__.py
